platform :ios, '7.0'
pod 'JBChartView', '~> 2.5.5'
pod 'TimesSquare', :git => 'https://github.com/jjojohjohn/objc-TimesSquare.git'
pod 'ODDPolynomial', :git => 'https://github.com/jjojohjohn/ODDPolynomial.git'
pod 'XYPieChart', :git => 'https://github.com/xyfeng/XYPieChart.git'
pod 'SSFlatDatePicker', :git => 'https://github.com/mattchiang777/FlatDatePicker.git'
pod 'MagicalRecord', :git => 'https://github.com/magicalpanda/MagicalRecord.git'
pod 'PromiseKit'
pod 'SBJson4', '~> 4.0.0'
pod 'pop', :git => 'https://github.com/facebook/pop.git'
pod 'GoogleAnalytics-iOS-SDK', '3.0.3c'
